### PR TITLE
Add gradle

### PR DESCRIPTION
**Pull request by murlock**
Hello 👋

Please found this PR that:
- Fix java code for constants (string and integer) that was self-referenced
- Fix some misuse of parent method without super
- Add compilation with Gradle and Java 1.8

At this time, JAR file can be launched but nothing appears

Let me know if you are interested

### CODE REVIEW

**Comment by shaner9er** [comment]
Woah.. you trying to make this playable?

**Comment by murlock** [comment]
Yes, at least first screen is loading and no more warning on startup by importing constants 🥳

The current state
image


But all mouse event is broken with Java 1.8, time to read documentation I guess 😄

**Comment by shaner9er** [comment]
> Yes, at least first screen is loading and no more warning on startup by importing constants 🥳
> 
> The current state image
> 
> But all mouse event is broken with Java 1.8, time to read documentation I guess 😄

I really hope you get this back in it's entirety I'd even front the hosting 😂

**Comment by murlock** [comment]
Despite mixed events systems, it is now possible to login (fake hero is used), visit stores and play few quests.
There is some errors:
- Font are too big
- Text renderer doesn't show it in multi line
- Storage in store doesn't work
- Window close works only on main screen, not on other screen

image

You can test it by downloading https://murlock.org/RustyDagger.jar 
and run 
```
$ java -jar RustyDagger
```

**Comment by reconSuave** [comment]
🎉🎉😀
This is so cool, thanks for the PR! 
Merged.

**Comment by dennooze** [comment]
https://github.com/reconSuave/RustyDagger/pull/2#issuecomment-1651190182

Is this editable file ? I tried opening up the JAR file in eclipse, but i'm sort of unable to view the source file for database.
I have intention to host this and make this multi-playerable + modifications to make it better. Anyone mind provide some guidance ?

**Comment by shaner9er** [comment]
> [#2 (comment)](https://github.com/reconSuave/RustyDagger/pull/2#issuecomment-1651190182)
> 
> Is this editable file ? I tried opening up the JAR file in eclipse, but i'm sort of unable to view the source file for database. I have intention to host this and make this multi-playerable + modifications to make it better. Anyone mind provide some guidance ?

goto this site and join the discord the guy who got this running might be able to help you https://dragoncourt.penguinchilling.com/DCourt/Game.html

**Pull request merged**
